[package]
name = "inner_html"
version = "0.1.0"
authors = ["CaptainSpof <captain.spof@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
yew = "0.18"
wasm-bindgen = "0.2.74"
getrandom = { version = "0.2", features = ["js"] }
random-ramble = { path = "../random-ramble/core" }

[dependencies.web-sys]
version = "0.3"
features = ["console", "Document", "Element", "Node", "Window"]

[build]
target = "wasm32-unknown-unknown"
